name: Get contribution

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  get-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get contribution
        run: |
          git log --author="$GITHUB_ACTOR" --since="1 week ago" --pretty=tformat: --numstat | \
          awk '{ add += $1 ; subs += $2 ; loc += $1 - $2 } END { printf "Added lines: %s\nRemoved lines : %s\nTotal lines : %s\n",add,subs,loc }' -
