name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: windows-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello World!"
            echo "hey!"
      - name: Print goodbye
        run: echo "Done-Bye!"
       
    
  
