name: Second Workflow 
on: push
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Get code 
        run: echo "Commit changes in the code"
      - name: Update 
        run: echo "Update the code" 
      
